apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluent
  namespace: default
spec:
  helmVersion: 3
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://hub.helm.sh/charts/fluent/fluentd
    version: 0.2.2
  values:
    replicas: 1