apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluent
  namespace: default
spec:
  helmVersion: "v3"
  releaseName: fluent-local
  chart:
    repository: https://fluent.github.io/helm-charts
    name: fluent/fluentd
    version: 0.2.2
  values:
    replicas: 1