apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bitnami-fluent
  namespace: default
spec:
  helmVersion: "v3"
  releaseName: fluent-local
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: fluentd
    version: 3.6.2
  values:
    replicas: 1